Don't crash when email message lacks Subject header
Normally email messages have subject headers, but if the user edits the
email in their editor and makes it empty (probably because they changed
their mind and don't want to send an email yet) then git-publish
crashes:

  Traceback (most recent call last):
    File "git-publish/git-publish", line 953, in <module>
      sys.exit(main())
    File "git-publish/git-publish", line 910, in main
      selected_patches = inspect_menu(tmpdir, to, cc, patches, suppress_cc,
    File "git-publish/git-publish", line 507, in inspect_menu
      print(m['Subject'].strip())
  AttributeError: 'NoneType' object has no attribute 'strip'

Skip printing the Subject header when it doesn't exist.

Signed-off-by: Stefan Hajnoczi <stefanha@gmail.com>