Decode patch selection NameTemporaryFile
After selecting "[s] Select patches to send (default: all)" and exiting
GIT_EDITOR after saving git publish, the following error is produced:

  Traceback (most recent call last):
    File "git-publish", line 914, in <module>
      sys.exit(main())
    File "git-publish", line 871, in main
      selected_patches = inspect_menu(tmpdir, to, cc, patches, suppress_cc,
    File "git-publish", line 468, in inspect_menu
      output = git_send_email(to_list, cc_list, patches, suppress_cc,
    File "git-publish", line 247, in git_send_email
      return _git_with_stderr(*args[1:])[0]
    File "git-publish", line 86, in _git_with_stderr
      print('git ' + ' '.join(args))
  TypeError: sequence item 9: expected str instance, bytes found

Decode the file when reading since NameTemporaryFiles are opened in
'w+b' mode by default.

Fixes: #101
Signed-off-by: Stefan Hajnoczi <stefanha@gmail.com>