Check the base branch
When the base branch does not exist, git-publish produces a pretty
cryptic error:
ERROR: git format-patch --subject-prefix PATCH --output-directory /tmp/tmps35kpt7n --no-cover-letter master..
fatal: ambiguous argument 'master..': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'

Improve the situation a bit with an early check, and some hint.

Signed-off-by: Marc-André Lureau <marcandre.lureau@redhat.com>